# Generated by Django 5.2.12 on 2026-03-07 20:41

import maxquant.rawtools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxquant', '0023_result_requeue_dispatch_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtoolssetup',
            name='rawtools_args',
            field=models.CharField(default='-p -q -x -u -l -m -r TMT11 -chro 12TB', max_length=256, null=True, validators=[maxquant.rawtools.validate_rawtools_args]),
        ),
    ]
